/**
 * Style Advisor - Garment Metadata Schema & Catalog Types
 * Matching PRD v4.2 specification and Zero-Hallucination Architecture.
 */

export type GarmentSlot = 'outerwear' | 'top' | 'bottom' | 'shoes' | 'accessory';

export type GenderCut =
  | 'male'
  | 'female'
  | 'neutral'
  | 'men'
  | 'women'
  | 'unisex';

export type BudgetTier =
  | '$'
  | '$$'
  | '$$$'
  | 'budget'
  | 'mid'
  | 'premium'
  | 'luxury';

export type ClothingSize = 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL';

export type SeasonOfWear =
  | 'all_season'
  | 'spring_summer'
  | 'fall_winter'
  | 'spring'
  | 'summer'
  | 'fall'
  | 'winter'
  | 'all-season';

export type Occasion =
  | 'pitch'
  | 'interview'
  | 'date'
  | 'family'
  | 'funeral'
  | 'court'
  | 'wedding'
  | 'work'
  | 'casual'
  | 'smart-casual'
  | 'business-casual'
  | 'formal'
  | 'date-night'
  | 'travel'
  | 'lounge'
  | 'outdoor';

export type BodyType =
  | 'rectangle'
  | 'bottom_triangle'
  | 'oval'
  | 'top_triangle'
  | 'double_triangle'
  | 'not_sure'
  | 'athletic'
  | 'slim'
  | 'average'
  | 'curvy'
  | 'tall'
  | 'petite'
  | 'plus'
  | 'inverted-triangle'
  | 'hourglass'
  | 'pear'
  | 'apple';

export type PaletteSeason =
  | 'winter'
  | 'summer'
  | 'autumn'
  | 'spring'
  | 'not_sure'
  | 'true_winter'
  | 'deep_winter'
  | 'cool_winter'
  | 'bright_winter'
  | 'true_summer'
  | 'light_summer'
  | 'soft_summer'
  | 'cool_summer'
  | 'true_autumn'
  | 'warm_autumn'
  | 'deep_autumn'
  | 'soft_autumn'
  | 'true_spring'
  | 'light_spring'
  | 'bright_spring'
  | 'warm_spring';

export type Complexion = 'dark' | 'medium' | 'light';

export type StyleOption =
  | 'casual'
  | 'sporty'
  | 'classic'
  | 'nerdy'
  | 'trendy'
  | 'fabulous'
  | string;

export type LifestyleTag =
  | 'new_grad'
  | 'family'
  | 'outdoors'
  | 'office_professional'
  | string;

export interface FabricDetails {
  composition: string;
  weave?: string;
  care: string;
  sustainable?: boolean;
}

export interface ReturnPolicy {
  window_days: number;
  free_returns: boolean;
  policy_note: string;
}

export interface Garment {
  /** Deterministic identifier (e.g. "ca_rwco_089", "ca_art_042") */
  id: string;
  garment_id?: string;
  /** Public title */
  name: string;
  /** Canadian / Partner brand name (e.g. "Aritzia", "RW&CO", "Lululemon", "Kotn", "Vessi", "Frank And Oak") */
  brand: string;
  /** Wardrobe category slot */
  slot: GarmentSlot;
  /** Price in CAD */
  price: number;
  price_cad?: number;
  /** Currency code, standard CAD */
  currency: 'CAD';
  /** Direct link to the brand's verified Canadian retailer page */
  product_url: string;
  retailer_url?: string;
  /** High-res optimized product image URL */
  image_url: string;
  /** Target gender silhouette / cut */
  gender_cut: GenderCut | GenderCut[];
  /** Budget categorization tier ($ / $$ / $$$ or budget / mid / luxury) */
  budget_tier: BudgetTier;
  /** Suitable wear occasions */
  occasions: Occasion[];
  /** Compatible seasonal color analysis palettes */
  palette_seasons: PaletteSeason[];
  /** Flattering body silhouettes */
  body_types: BodyType[];
  /** Associated style tags (classic, casual, trendy, sporty, nerdy, fabulous) */
  styles?: StyleOption[];
  /** Weather & climate season compatibility */
  season_of_wear: SeasonOfWear[];
  /** Formality level (1 to 5) or score (1 to 10) */
  formality_level?: number;
  formality_score: number;
  /** Available size spectrum (e.g. "XS - XXL", "28W - 38W") */
  size_range?: string;
  /** Primary color name */
  color?: string;
  /** Hex color for swatch rendering */
  hex_color?: string;
  /** Fabric & composition information */
  fabric: string | FabricDetails;
  /** Merchant return policy */
  return_policy: string | ReturnPolicy;
  /** Product description */
  description?: string;
  /** Stylist rationale and pairing notes */
  styling_notes?: string;
  /** Stock availability status */
  in_stock: boolean;
  /** Ingestion or verification ISO date (e.g. "2026-10-10") */
  verified_date?: string;
}

/**
 * Filter payload used for candidate retrieval before LLM scoring.
 */
export interface CatalogFilterCriteria {
  gender_cut: GenderCut;
  budget_tier?: BudgetTier[];
  max_price?: number;
  occasions?: Occasion[];
  season_of_wear?: SeasonOfWear[];
  palette_season?: PaletteSeason;
  body_type?: BodyType;
  style?: StyleOption;
  lifestyle?: LifestyleTag[];
  slots?: GarmentSlot[];
  brands?: string[];
  size?: ClothingSize;
}

/**
 * Outfit recommendation bundle returned by the AI Engine.
 */
export interface OutfitRecommendation {
  outfit_id: string;
  title: string;
  /** Formality calibrated score of the overall ensemble (1-10) */
  overall_formality: number;
  /** Editorial reasoning generated by LLM (rendered in Newsreader serif) */
  reasoning: string;
  /** IDs of selected garments matching the candidate pool */
  garment_ids: {
    outerwear?: string;
    top: string;
    bottom: string;
    shoes: string;
    accessory?: string;
  };
  /** Estimated total outfit cost in CAD */
  total_price_cad: number;
  /** Any caution / disclosure notes */
  caution_notes?: string[];
}

/**
 * Core User Profile representing the 9 persistent onboarding variables (PRD FR-1).
 */
export interface UserProfile {
  // 1. Gender expression (Female · Neutral · Male)
  gender_cut?: GenderCut;
  gender_expression?: 'Female' | 'Neutral' | 'Male' | GenderCut;

  // 2. Budget ($ · $$ · $$$) - Hard constraint
  budget_tier?: BudgetTier | BudgetTier[];
  budget?: '$' | '$$' | '$$$' | BudgetTier;

  // 3. Size (XS - XXL) - Soft preference
  size?: ClothingSize;

  // 4. Body Type (5 neutral silhouettes + Not sure)
  body_type?: BodyType;

  // 5. Seasonal Colour (4-season wheel + Not sure)
  palette_season?: PaletteSeason;
  seasonal_colour?: PaletteSeason;

  // 6. Complexion (Dark · Medium · Light) - Optional
  complexion?: Complexion;

  // 7. Style (Casual · Sporty · Classic · Nerdy · Trendy · Fabulous)
  preferred_styles?: StyleOption[];
  style?: StyleOption;

  // 8. Season or Climate (Spring/Summer · Fall/Winter)
  season_of_wear?: SeasonOfWear;
  season_or_climate?: 'Spring/Summer' | 'Fall/Winter' | SeasonOfWear;

  // 9. Lifestyle (Multi-select up to 2: New Grad, Family, Outdoors, Office Professional)
  lifestyle_tags?: LifestyleTag[];
  lifestyle?: LifestyleTag[];

  // User persistence & Wardrobe checklist
  owned_item_ids?: string[];
  email?: string;
}

export type NudgeType = 'too_formal' | 'too_casual' | 'not_me';

/**
 * Occasion Flow (Flow A) specific input.
 */
export interface OccasionInput {
  flow?: 'occasion' | 'flow_a';
  occasion: Occasion;
  season_of_wear: SeasonOfWear;
  audience_text?: string;
  formality_target?: number;
  style?: StyleOption;
  nudge?: NudgeType;
}

/**
 * Everyday Flow (Flow B) specific input.
 */
export interface EverydayInput {
  flow: 'everyday' | 'flow_b';
  season_of_wear: SeasonOfWear;
  lifestyle?: LifestyleTag[];
  occasions?: Occasion[];
}

export type CandidateFilterInput = UserProfile & {
  flow?: 'occasion' | 'flow_a' | 'everyday' | 'flow_b';
  occasion?: Occasion;
  season_of_wear?: SeasonOfWear;
  audience_text?: string;
  formality_target?: number;
  style?: StyleOption;
  nudge?: NudgeType;
  lifestyle?: LifestyleTag[];
  occasions?: Occasion[];
};

export type RelaxedField = 'palette' | 'style' | 'lifestyle';

export interface FilterCandidatesResult {
  candidate_ids_by_slot: Record<GarmentSlot, string[]>;
  candidates_by_slot: Record<GarmentSlot, Garment[]>;
  all_candidate_ids: string[];
  total_candidates: number;
  slot_counts: Record<GarmentSlot, number>;
  relaxed_field: RelaxedField | null;
  relaxed_fields: RelaxedField[];
  is_valid_pool: boolean; // True if all required slots (outerwear, top, bottom, shoes) have at least 1 item
}

export interface LLMRecommendationPayload {
  calibration: {
    formality_score: number; // 1-5 or 1-10
    formality_target?: number;
    signal?: string;
    notes?: string;
    audience_read?: string;
    risk_assessment?: string;
  };
  interpretation_summary: string;
  selected_garment_ids: {
    outerwear?: string | null;
    top: string;
    bottom: string;
    shoes: string;
    accessory?: string | null;
  };
  reasoning: string;
  override_applied?: string | null | boolean;
  caution_notes?: string[];
}

export interface RecommendApiResponse {
  success: boolean;
  cached?: boolean;
  data?: {
    calibration: {
      formality_score: number;
      formality_target?: number;
      signal?: string;
      notes?: string;
      audience_read?: string;
      risk_assessment?: string;
    };
    interpretation_summary: string;
    selected_garments: {
      outerwear?: Garment;
      top: Garment;
      bottom: Garment;
      shoes: Garment;
      accessory?: Garment;
    };
    selected_garment_ids: {
      outerwear?: string | null;
      top: string;
      bottom: string;
      shoes: string;
      accessory?: string | null;
    };
    total_price_cad: number;
    reasoning: string;
    override_applied?: string | null | boolean;
    caution_notes: string[];
    filter_metadata: {
      relaxed_field: RelaxedField | null;
      relaxed_fields: RelaxedField[];
      total_candidates: number;
    };
  };
  error?: string;
  message?: string;
}
