/**
 * Style Advisor - Garment Metadata Schema & Catalog Types
 * Matching PRD Section 6.1 specification and Core Architectural Laws.
 */

export type GarmentSlot = 'outerwear' | 'top' | 'bottom' | 'shoes' | 'accessory';

export type GenderCut = 'men' | 'women' | 'unisex';

export type BudgetTier = 'budget' | 'mid' | 'premium' | 'luxury';

export type SeasonOfWear = 'spring' | 'summer' | 'fall' | 'winter' | 'all-season';

export type Occasion =
  | 'casual'
  | 'smart-casual'
  | 'business-casual'
  | 'formal'
  | 'pitch'
  | 'work'
  | 'date-night'
  | 'travel'
  | 'lounge'
  | 'outdoor';

export type BodyType =
  | 'athletic'
  | 'slim'
  | 'average'
  | 'curvy'
  | 'tall'
  | 'petite'
  | 'plus'
  | 'inverted-triangle'
  | 'hourglass'
  | 'rectangle'
  | 'pear'
  | 'apple';

export type PaletteSeason =
  // 4 Primary seasonal groups
  | 'winter'
  | 'summer'
  | 'autumn'
  | 'spring'
  // 12 Detailed Flow subtypes
  | 'true_winter'
  | 'deep_winter'
  | 'cool_winter'
  | 'bright_winter'
  | 'true_summer'
  | 'light_summer'
  | 'soft_summer'
  | 'cool_summer'
  | 'true_autumn'
  | 'warm_autumn'
  | 'deep_autumn'
  | 'soft_autumn'
  | 'true_spring'
  | 'light_spring'
  | 'bright_spring'
  | 'warm_spring';

export interface FabricDetails {
  /** Primary material description (e.g., "100% Egyptian Cotton", "Wool-Cashmere Blend") */
  composition: string;
  /** Breathability / weight / weave note */
  weave?: string;
  /** Care instructions summary */
  care: string;
  /** Ethical or sustainability certification */
  sustainable?: boolean;
}

export interface ReturnPolicy {
  /** Return window in days */
  window_days: number;
  /** Whether returns are free/prepaid */
  free_returns: boolean;
  /** Human-readable policy breakdown */
  policy_note: string;
}

export interface Garment {
  /** Unique deterministic identifier (e.g. "aritzia-agency-blazer-01") */
  id: string;
  /** Garment public title */
  name: string;
  /** Canadian / Partner brand name (e.g. "Aritzia", "RW&CO", "Lululemon", "Kotn", "Vessi") */
  brand: string;
  /** Wardrobe category slot */
  slot: GarmentSlot;
  /** Price in CAD */
  price: number;
  /** Currency code, standard CAD */
  currency: 'CAD';
  /** Direct link to the brand's verified product page */
  product_url: string;
  /** Optimized product image URL */
  image_url: string;
  /** Target gender silhouette / cut */
  gender_cut: GenderCut;
  /** Budget categorization */
  budget_tier: BudgetTier;
  /** Suitable wear occasions */
  occasions: Occasion[];
  /** Compatible seasonal color analysis palettes */
  palette_seasons: PaletteSeason[];
  /** Flattering body silhouettes */
  body_types: BodyType[];
  /** Weather & climate season compatibility */
  season_of_wear: SeasonOfWear[];
  /** Formality calibration score (1 = ultra-casual loungewear, 10 = black-tie formal) */
  formality_score: number;
  /** Primary color name */
  color: string;
  /** Approximate hex color for UI swatch rendering */
  hex_color: string;
  /** Detailed fabric & care information */
  fabric: FabricDetails;
  /** Merchant return terms */
  return_policy: ReturnPolicy;
  /** Curated product description */
  description: string;
  /** Stylist rationale and pairing notes */
  styling_notes?: string;
  /** Stock availability status */
  in_stock: boolean;
}

/**
 * Filter payload used for candidate retrieval before LLM scoring.
 */
export interface CatalogFilterCriteria {
  gender_cut: GenderCut;
  budget_tier?: BudgetTier[];
  max_price?: number;
  occasions?: Occasion[];
  season_of_wear?: SeasonOfWear[];
  palette_season?: PaletteSeason;
  body_type?: BodyType;
  slots?: GarmentSlot[];
  brands?: string[];
}

/**
 * Outfit recommendation bundle returned by the AI Engine.
 */
export interface OutfitRecommendation {
  outfit_id: string;
  title: string;
  /** Formality calibrated score of the overall ensemble (1-10) */
  overall_formality: number;
  /** Editorial reasoning generated by LLM (rendered in Newsreader serif) */
  reasoning: string;
  /** IDs of selected garments matching the candidate pool */
  garment_ids: {
    outerwear?: string;
    top: string;
    bottom: string;
    shoes: string;
    accessory?: string;
  };
  /** Estimated total outfit cost in CAD */
  total_price_cad: number;
  /** Any caution / disclosure notes (e.g. dry-clean only, specific fit warning) */
  caution_notes?: string[];
}

/**
 * Core User Profile representing the 9 persistent onboarding variables.
 */
export interface UserProfile {
  gender_cut: GenderCut;
  budget_tier: BudgetTier | BudgetTier[];
  body_type?: BodyType;
  palette_season?: PaletteSeason;
  preferred_styles?: string[];
  lifestyle_tags?: string[];
  season_of_wear?: SeasonOfWear;
  owned_item_ids?: string[];
  email?: string;
}

export type NudgeType = 'too_formal' | 'too_casual' | 'not_me';

/**
 * Occasion Flow (Flow A) specific input.
 */
export interface OccasionInput {
  flow?: 'occasion' | 'flow_a';
  occasion: Occasion;
  season_of_wear: SeasonOfWear;
  audience_text?: string;
  formality_target?: number;
  style?: string;
  nudge?: NudgeType;
}

/**
 * Everyday Flow (Flow B) specific input.
 */
export interface EverydayInput {
  flow: 'everyday' | 'flow_b';
  season_of_wear: SeasonOfWear;
  lifestyle?: string[];
  occasions?: Occasion[];
}

export type CandidateFilterInput = UserProfile & {
  flow?: 'occasion' | 'flow_a' | 'everyday' | 'flow_b';
  occasion?: Occasion;
  season_of_wear?: SeasonOfWear;
  audience_text?: string;
  formality_target?: number;
  style?: string;
  nudge?: NudgeType;
  lifestyle?: string[];
  occasions?: Occasion[];
};

export type RelaxedField = 'palette' | 'style' | 'lifestyle';

export interface FilterCandidatesResult {
  candidate_ids_by_slot: Record<GarmentSlot, string[]>;
  candidates_by_slot: Record<GarmentSlot, Garment[]>;
  all_candidate_ids: string[];
  total_candidates: number;
  slot_counts: Record<GarmentSlot, number>;
  relaxed_field: RelaxedField | null;
  relaxed_fields: RelaxedField[];
  is_valid_pool: boolean; // True if all required slots (outerwear, top, bottom, shoes) have at least 1 item
}

export interface LLMRecommendationPayload {

  calibration: {
    formality_target: number; // 1-10
    audience_read: string;
    risk_assessment: string;
  };
  interpretation_summary: string;
  selected_garment_ids: {
    outerwear?: string;
    top: string;
    bottom: string;
    shoes: string;
    accessory?: string;
  };
  reasoning: string;
  override_applied: boolean;
  caution_notes?: string[];
}

export interface RecommendApiResponse {
  success: boolean;
  cached?: boolean;
  data?: {
    calibration: {
      formality_target: number;
      audience_read: string;
      risk_assessment: string;
    };
    interpretation_summary: string;
    selected_garments: {
      outerwear?: Garment;
      top: Garment;
      bottom: Garment;
      shoes: Garment;
      accessory?: Garment;
    };
    selected_garment_ids: {
      outerwear?: string;
      top: string;
      bottom: string;
      shoes: string;
      accessory?: string;
    };
    total_price_cad: number;
    reasoning: string;
    override_applied: boolean;
    caution_notes: string[];
    filter_metadata: {
      relaxed_field: RelaxedField | null;
      relaxed_fields: RelaxedField[];
      total_candidates: number;
    };
  };
  error?: string;
  message?: string;
}


