-- ==========================================================
-- Style Advisor PostgreSQL Database Backup (.sql)
-- Exported At: 2026-09-27T02:03:18.428Z
-- Total Records: 27
-- To restore directly into Postgres: psql $POSTGRES_URL < backup-postgres.sql
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS garments (
  id VARCHAR(100) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  brand VARCHAR(100) NOT NULL,
  slot VARCHAR(50) NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  currency VARCHAR(10) DEFAULT 'CAD',
  product_url TEXT,
  image_url TEXT,
  gender_cut VARCHAR(50) DEFAULT 'unisex',
  budget_tier VARCHAR(50) DEFAULT 'mid',
  occasions JSONB DEFAULT '["work", "casual", "smart-casual"]'::jsonb,
  palette_seasons JSONB DEFAULT '["autumn", "winter"]'::jsonb,
  body_types JSONB DEFAULT '["average", "athletic"]'::jsonb,
  season_of_wear JSONB DEFAULT '["all-season", "fall"]'::jsonb,
  formality_score SMALLINT DEFAULT 6,
  color VARCHAR(100) DEFAULT 'Classic',
  hex_color VARCHAR(20) DEFAULT '#2C2C2C',
  fabric JSONB DEFAULT '{"composition": "Premium Canadian Fabric Blend", "care": "Machine wash cold"}'::jsonb,
  return_policy JSONB DEFAULT '{"window_days": 30, "free_returns": true}'::jsonb,
  description TEXT,
  styling_notes TEXT,
  in_stock BOOLEAN DEFAULT true,
  verified_date VARCHAR(20),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_garments_slot ON garments(slot);
CREATE INDEX IF NOT EXISTS idx_garments_brand ON garments(brand);

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_rwco_201',
  'Unstructured Knit Wool-Blend Blazer',
  'RW&CO',
  'outerwear',
  198,
  'CAD',
  'https://www.rw-co.com/en/unstructured-knit-blazer/463912.html',
  'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
  'male',
  '$$',
  '["pitch","interview","family","date","work","court","funeral"]'::jsonb,
  '["winter","autumn","summer","spring"]'::jsonb,
  '["rectangle","oval","top_triangle"]'::jsonb,
  '["all_season","fall_winter"]'::jsonb,
  7,
  'Classic',
  '#2C2C2C',
  '{"composition":"60% Wool, 40% Technical Poly Jersey"}'::jsonb,
  '{"window_days":30,"free_returns":true}'::jsonb,
  'Soft-shouldered unstructured tailoring providing razor sharp lines without corporate rigidity.',
  'The core weapon for Persona Sam: satisfies VC room expectations while respecting developer roots.',
  true,
  '2026-10-10',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_ves_003',
  'Everyday Classic Waterproof Sneaker',
  'Vessi',
  'shoes',
  145,
  'CAD',
  'https://ca.vessi.com/products/mens-everyday-classic-all-black',
  'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
  'male',
  '$$',
  '["pitch","casual","travel","work","family","interview"]'::jsonb,
  '["winter","summer","autumn","spring"]'::jsonb,
  '["rectangle","oval","top_triangle","bottom_triangle"]'::jsonb,
  '["all_season","spring_summer","fall_winter"]'::jsonb,
  5,
  'Classic',
  '#2C2C2C',
  '{"composition":"Patented Dyma-tex 100% Waterproof Knit Membrane"}'::jsonb,
  '{"window_days":30,"free_returns":true}'::jsonb,
  'Vancouver-invented 100% waterproof breathable knit sneakers that conquer rain puddles cleanly.',
  'The ultimate Vancouver footwear: keeps socks dry while matching dark tapered trousers.',
  true,
  '2026-10-10',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_art_042',
  'The Effortless Pant - Crepette',
  'Aritzia',
  'bottom',
  148,
  'CAD',
  'https://www.aritzia.com/en/product/the-effortless-pant/77775.html',
  'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80',
  'female',
  '$$',
  '["interview","pitch","court","date","family","work","funeral"]'::jsonb,
  '["winter","autumn","summer","spring"]'::jsonb,
  '["rectangle","bottom_triangle","oval","double_triangle","top_triangle"]'::jsonb,
  '["all_season","spring_summer","fall_winter"]'::jsonb,
  8,
  'Classic',
  '#2C2C2C',
  '{"composition":"100% Japanese Crepette (Wrinkle-Resistant)"}'::jsonb,
  '{"window_days":30,"free_returns":true}'::jsonb,
  'Aritzia’s world-renowned high-waisted wide-leg tailored trouser with fluid drape.',
  'Pairs with tucked knitwear and sharp ankle boots for commanding boardroom authority.',
  true,
  '2026-10-10',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_the-super-puff-_the-super-puff-o-rai_6564',
  'The Super Puff₂O™ - Rainstop™',
  'The Super Puff™',
  'outerwear',
  398,
  'CAD',
  'https://www.aritzia.com/en/product/the-super-puff%E2%82%82o%E2%84%A2/126385.html?color=11884',
  'https://assets.aritzia.com/image/upload/c_crop,ar_1920:2623,g_south/q_auto,f_auto,dpr_auto/f26_a05_126385_11884_off_a',
  'unisex',
  'luxury',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  8,
  'Classic',
  '#cba8a9',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at The Super Puff™.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by The Super Puff™ for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_lululemon_women-s-wunder-puff-_7096',
  'Women''s Wunder Puff Bomber Vest',
  'Lululemon',
  'outerwear',
  268,
  'CAD',
  'https://shop.lululemon.com/en-ca/p/womens-wunder-puff-bomber-vest/l8522sltpg',
  'https://images.lululemon.com/is/image/lululemon/LW4CPRS_074110_1',
  'women',
  'premium',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  8,
  'ColourMahogany MuseMahogany Muse',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Lululemon.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Lululemon for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_aritzia_interlock-cotton-fun_0191',
  'InterLock Cotton Function T-Shirt',
  'Aritzia',
  'top',
  40,
  'CAD',
  'https://www.aritzia.com/en/product/interlock-cotton-function-t-shirt/124059.html',
  'https://assets.aritzia.com/image/upload/c_crop,ar_1920:2623,g_south/q_auto,f_auto,dpr_auto/f26_a01_124059_1275_off_a',
  'unisex',
  'budget',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  6,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Aritzia.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Aritzia for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_canada-goose_mira-bomber_1804',
  'Mira Bomber',
  'Canada Goose',
  'outerwear',
  1895,
  'CAD',
  'https://www.canadagoose.com/en-ca/products/mira-bomber-1739w',
  'https://cdn.shopify.com/s/files/1/0761/4686/8448/files/1739W_9110_on_front_01.jpg?v=1789417563',
  'unisex',
  'luxury',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  8,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Canada Goose.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Canada Goose for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_arc-teryx_beta-ar-jacket-women_7952',
  'Beta AR Jacket Women''s',
  'Arc''teryx',
  'outerwear',
  840,
  'CAD',
  'https://arcteryx.com/ca/en/shop/womens/beta-ar-jacket-9863',
  'https://images-dynamic-arcteryx.imgix.net/details/1350x1710/F26-X000009863-Beta-AR-Jacket-Black-Women-s-Front-View.jpg',
  'women',
  'luxury',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  8,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Contrast: 3L GORE-TEX® PRO ePE Beam Dyed 80d plain weave recycled nylon, 126 gsm, C0 DWR - 100% Nylon with ePE and PU Membrane 100% Nylon Backing, Body: 100d 3L GORE-TEX® PRO ePE, recycled plain weave, 135 gsm, FC0 DWR - 100% Nylon with ePE and PU Membrane 100% Nylon Backing, Origin of fabric: CHINA, Origin of dyeing: CHINA, Origin of Manufacture: VIETNAM, May release plastic microfibres into the environment when washing","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Arc''teryx.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Arc''teryx for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_roots_womens-plastic-squar_6349',
  'Womens Plastic Square Aviator Sunglasses',
  'Roots',
  'accessory',
  26.25,
  'CAD',
  'https://www.roots.com/ca/en/womens-plastic-square-aviator-sunglasses-42040101.html',
  'https://www.roots.com/dw/image/v2/BGGS_PRD/on/demandware.static/-/Sites-roots_master_catalog/default/dw45e8d34d/images/42040101_001_a.jpg?sw=1200&sh=1200&sm=fit',
  'women',
  'budget',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  6,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Roots.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Roots for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_kotn_men-apos-s-ali-crewn_9419',
  'Men''s Ali Crewneck Sweater in Juniper/Cream',
  'Kotn',
  'top',
  198,
  'CAD',
  'https://kotn.com/products/mens-ali-crewneck-sweater',
  'https://cdn.shopify.com/s/files/1/0932/1356/files/MENS_ALI_CREWNECK_SWEATER_JUNIPER_CREAM_02.jpg?v=1789669307',
  'men',
  'premium',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  6,
  'Juniper/Cream',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Kotn.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Kotn for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_mackage_tripp_6046',
  'TRIPP',
  'Mackage',
  'outerwear',
  1090,
  'CAD',
  'https://www.mackage.ca/products/tripp',
  'http://www.mackage.ca/cdn/shop/files/TRIPP_BLACK_1.jpg?v=1787832027&width=2048',
  'unisex',
  'luxury',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  8,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Mackage.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Mackage for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_moose-knuckles_tegan-down-bomber-ja_1253',
  'TEGAN DOWN BOMBER JACKET-ASHEN',
  'Moose Knuckles',
  'outerwear',
  595,
  'CAD',
  'https://www.mooseknucklescanada.com/products/tegan-down-bomber-jacket-m35lb046-1968',
  'http://www.mooseknucklescanada.com/cdn/shop/files/m35lb046_1968_front_category.jpg?v=1789053376',
  'unisex',
  'luxury',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  8,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Moose Knuckles.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Moose Knuckles for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_herschel-supply_yara-large-shoulder-_6373',
  'Yara Large Shoulder Bag',
  'Herschel Supply Co.',
  'accessory',
  68.99,
  'CAD',
  'https://herschel.ca/products/yara-large-shoulder-bag',
  'https://herschel.ca/cdn/shop/files/11525-00001-os-01-IxKbQ2of.jpg?v=1781474914&width=480',
  'unisex',
  'budget',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  6,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Herschel Supply Co..","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Herschel Supply Co. for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_province-of-can_support-the-canadian_9367',
  'Support the Canadian Girls Baseball Hat Pink',
  'Province of Canada',
  'accessory',
  56,
  'CAD',
  'https://provinceofcanada.com/collections/new-arrivals/products/support-the-canadian-girls-baseball-hat-pink',
  'https://provinceofcanada.com/cdn/shop/files/Lead-Dark-Pink-Support-The-Canadian-Girls-Baseball-Hat-1S8A5375_5071ac79-ba45-4e4a-b00a-f75bbd13f075.jpg?v=1790346411&width=1920',
  'unisex',
  'budget',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  6,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Province of Canada.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Province of Canada for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_encircled_the-airy-gauze-rever_7853',
  'The Airy Gauze Reversible Blouse',
  'Encircled',
  'top',
  168,
  'CAD',
  'https://www.encircled.ca/collections/new/products/the-airy-gauze-reversible-blouse',
  'http://www.encircled.ca/cdn/shop/files/TheAiryGauzeReversibleBlouseMarine1.jpg?v=1787941684',
  'women',
  'mid',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  6,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Encircled.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Encircled for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_frank-and-oak_rugby-polo_4072',
  'RUGBY POLO',
  'Frank And Oak',
  'top',
  53.4,
  'CAD',
  'https://www.frankandoak.com/collections/sale-mens/products/mens-knit-sweater-canvas-classic-navy-2mkt008fe-navsun',
  'http://www.frankandoak.com/cdn/shop/files/2MKT008FE-CLASSICNAVY-1.jpg?crop=center&height=1200&v=1772555813&width=1200',
  'men',
  'budget',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  6,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Frank And Oak.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Frank And Oak for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_club-monaco_bowee-tee_3204',
  'Bowee Tee',
  'Club Monaco',
  'top',
  48,
  'CAD',
  'https://www.clubmonaco.ca/products/bowee-tee-295812894-103',
  'https://cdn.shopify.com/s/files/1/0570/2719/9048/files/295102559-022_0main.jpg?v=1763599303',
  'unisex',
  'budget',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  7,
  'Black',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Club Monaco.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Club Monaco for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_simons_floral-embossed-card_4574',
  'Floral embossed cardigan',
  'Simons',
  'outerwear',
  89,
  'CAD',
  'https://www.simons.ca/en/men-clothing/sweaters/shawls-cardigans/floral-embossed-cardigan--15233-231269',
  'https://imagescdn.simons.ca/images/15233-231269-15-A1_2/floral-embossed-cardigan.jpg?__=10',
  'men',
  'mid',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  8,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Simons.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Simons for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_vessi_100-waterproof-shoes_8984',
  '100% Waterproof Shoes, Sneakers & Boots | Vessi',
  'Vessi',
  'shoes',
  180,
  'CAD',
  'https://ca.vessi.com/',
  'https://ca.vessi.com/cdn/shop/files/Social_Sharing_Thumbnail_-_Rebrand-2025_1c23f636-4091-46bc-9661-afb33073a05f.jpg?crop=center&height=630&v=1757995231&width=1200',
  'unisex',
  'mid',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  6,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Vessi.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Vessi for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_naked-famous-de_gracie-jacket-organi_0594',
  'Gracie Jacket - Organic Hickory',
  'Naked & Famous Denim',
  'outerwear',
  228,
  'CAD',
  'https://nakedandfamousdenim.com/products/gracie-organic-hickory-1',
  'https://nakedandfamousdenim.com/cdn/shop/files/365142993_A.jpg?v=1769460628&width=1920',
  'unisex',
  'premium',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  7,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Naked & Famous Denim.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Naked & Famous Denim for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_lol-_just-insulated-vest_2029',
  'Just Insulated Vest',
  'Lolë',
  'outerwear',
  139,
  'CAD',
  'https://lolelife.com/en-ca/collections/weightless/products/just-insulated-vest-luw0900',
  'https://lolelife.com/cdn/shop/files/LUW0900_N415_1.jpg?v=1761326861&width=1920',
  'unisex',
  'mid',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  8,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Lolë.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Lolë for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_common-goods_alta-legging_3293',
  'Alta Legging',
  'Common Goods',
  'bottom',
  40,
  'CAD',
  'https://commongoods.ca/products/tentree-canada-alta-legging-8206630354997',
  'http://commongoods.ca/cdn/shop/files/Black-Women_sBlackHigh-RiseLegging-TCW4429-0164_4.jpg?v=1785867632',
  'unisex',
  'budget',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  7,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Common Goods.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Common Goods for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_reigning-champ_cotton-flannel-highl_5097',
  'Cotton Flannel Highland Shirt',
  'Reigning Champ',
  'top',
  168,
  'CAD',
  'https://ca.reigningchamp.com/products/cotton-flannel-highland-shirt-arctic-wolf-oxide',
  'https://ca.reigningchamp.com/cdn/shop/files/FW26_RC-8074_ARCTICWOLF-OXIDE_SHIRTING_off_1.jpg?v=1788296795&width=1920',
  'unisex',
  'mid',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  6,
  'Arctic Wolf/Oxide',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"cotton flannel","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Reigning Champ.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Reigning Champ for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_rw-co_3-4-sleeve-boat-neck_2217',
  '3/4-Sleeve Boat-Neck Top',
  'RW&CO',
  'top',
  32.13,
  'CAD',
  'https://www.rw-co.com/products/knit-pullover-boat-neck-3-4-sleeve-496723',
  'http://www.rw-co.com/cdn/shop/files/740ddcb9862ad731867ef4e2050fd1ab47a7aa59_496723_1_B.jpg?v=1776734210',
  'unisex',
  'budget',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  6,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at RW&CO.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by RW&CO for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_rw-co_slim-fit-prince-of-w_1772',
  'Slim-Fit Prince-of-Wales Pant',
  'RW&CO',
  'bottom',
  90.93,
  'CAD',
  'https://www.rw-co.com/products/slim-fit-wool-blend-prince-of-wales-pant-496955',
  'http://www.rw-co.com/cdn/shop/files/d73e4e13b9daa20a75012b0b525899f4792ee8a2_496955_278_B.jpg?v=1784552666',
  'unisex',
  'mid',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  7,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at RW&CO.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by RW&CO for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_rw-co_tailored-fit-striped_1107',
  'Tailored-Fit Striped Brown Wool Suit Pant',
  'RW&CO',
  'bottom',
  179,
  'CAD',
  'https://www.rw-co.com/products/tailored-brown-pinstripe-wool-blend-pant-497318',
  'http://www.rw-co.com/cdn/shop/files/0780fa0b81f2ffdc07002659824bcb54fd2d4bd1_497318_913_B.jpg?v=1785762211',
  'unisex',
  'mid',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  7,
  'Classic',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Premium Canadian Fabric Blend","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at RW&CO.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by RW&CO for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO garments (
  id, name, brand, slot, price, currency, product_url, image_url,
  gender_cut, budget_tier, occasions, palette_seasons, body_types,
  season_of_wear, formality_score, color, hex_color, fabric,
  return_policy, description, styling_notes, in_stock, verified_date, updated_at
) VALUES (
  'ca_lululemon_define-cropped-jacke_8072',
  'Define Cropped Jacket Nulu',
  'Lululemon',
  'outerwear',
  138,
  'CAD',
  'https://shop.lululemon.com/en-ca/p/nulu-cropped-define-jacket/oo2vz3qc01',
  'https://images.lululemon.com/is/image/lululemon/LW3HWES_074115_1',
  'unisex',
  'mid',
  '["work","smart-casual","casual"]'::jsonb,
  '["autumn","winter"]'::jsonb,
  '["average","athletic"]'::jsonb,
  '["all-season","fall"]'::jsonb,
  8,
  'ColourTrue Leopard Black MultiTrue Leopard Black Multi',
  '#1c1b19',
  '{"care":"Machine wash cold. Hang dry.","composition":"Nulu","sustainable":false}'::jsonb,
  '{"policy_note":"Free returns and exchanges within 30 days at Lululemon.","window_days":30,"free_returns":true}'::jsonb,
  'Crafted by Lululemon for refined wardrobe versatility in Canadian climates.',
  'Pairs seamlessly with tailored foundation pieces.',
  true,
  '2026-09-26',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  slot = EXCLUDED.slot,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  product_url = EXCLUDED.product_url,
  image_url = EXCLUDED.image_url,
  gender_cut = EXCLUDED.gender_cut,
  budget_tier = EXCLUDED.budget_tier,
  occasions = EXCLUDED.occasions,
  palette_seasons = EXCLUDED.palette_seasons,
  body_types = EXCLUDED.body_types,
  season_of_wear = EXCLUDED.season_of_wear,
  formality_score = EXCLUDED.formality_score,
  color = EXCLUDED.color,
  hex_color = EXCLUDED.hex_color,
  fabric = EXCLUDED.fabric,
  return_policy = EXCLUDED.return_policy,
  description = EXCLUDED.description,
  styling_notes = EXCLUDED.styling_notes,
  in_stock = EXCLUDED.in_stock,
  verified_date = EXCLUDED.verified_date,
  updated_at = CURRENT_TIMESTAMP;

COMMIT;